server:
  port: 9081

spring:
  main:
    web-application-type: reactive

azure:
  queue:
    name: "orders"
    max-messages: 10
    connection-string: "${CONNECTION-ORDERS}"

  blob:
    name: "audit"
    connection-string: "${CONNECTION-ORDERS}"

  cosmos:
    uri: "${COSMOS-URI}"
    key: "${COSMOS-KEY}"
    database-name: "${COSMOS-DATABASE}"
    container-name: "${COSMOS-CONTAINER-NAME}"
    partition-key-path: "${COSMOS-PARTITION-KEY-PATH}"

audit:
  file:
    success: "ORDER_%s_FECHA_%s_UUID_%s.json"
    error: "ERROR_%s.txt"